language: haskell
env:
  global:
  - ELM_HOME="./elm-home"
install:
  - wget http://JoeyEremondi.github.io/elm-travis-cache/elm
  - wget http://JoeyEremondi.github.io/elm-travis-cache/elm-get
  - wget http://JoeyEremondi.github.io/elm-travis-cache/elm_home.tar.gz
  - chmod +x ./elm
  - chmod +x ./elm-get
  - tar -xzf elm_home.tar.gz ./
  - git clone git://github.com/maxsnew/IO
  - cd IO
  - cabal install
  - sudo ln -s ~/.cabal/bin/elm-io /usr/local/bin/elm-io
  - cd ..
  - echo "y" | ./elm-get install evancz/automaton
  - echo "y" | ./elm-get install deadfoxygrandpa/Elm-Test
  - npm install jsdom
before_script: elm-io --default-ports Tests/NodeTests.elm tests.js
script:
  - ./elm --make Demo.elm
  - node --stack-size=32000 tests.js
after_script:
  - git clone git://github.com/deadfoxygrandpa/Elm-Benchmark
  - cd Elm-Benchmark
  - cabal install
  - sudo ln -s ~/.cabal/bin/elm-benchmark /usr/local/bin/elm-benchmark
  - cd ..
  - elm-benchmark Tests/Benchmark.elm benchmark.js
  - npm install benchmark
  - node --stack-size=32000 benchmark.js
