language: haskell
install:
  - cabal install attoparsec-0.11.3.4
  - cabal install elm-get
  - sudo ln -s ~/.cabal/bin/elm /usr/local/bin/elm
  - sudo ln -s ~/.cabal/bin/elm-get /usr/local/bin/elm-get
  - git clone git://github.com/maxsnew/IO
  - cd IO
  - cabal install
  - sudo ln -s ~/.cabal/bin/elm-io /usr/local/bin/elm-io
  - cd ..
  - echo "y" | elm-get install evancz/automaton
  - echo "y" | elm-get install deadfoxygrandpa/Elm-Test
  - npm install jsdom
before_script: elm-io --default-ports Tests/NodeTests.elm tests.js
script:
  - elm --make Demo.elm
  - node --stack-size=32000 tests.js
after_script:
  - git clone git://github.com/deadfoxygrandpa/Elm-Benchmark
  - cd Elm-Benchmark
  - cabal install
  - sudo ln -s ~/.cabal/bin/elm-benchmark /usr/local/bin/elm-benchmark
  - cd ..
  - elm-benchmark Tests/Benchmark.elm benchmark.js
  - npm install benchmark
  - node --stack-size=32000 benchmark.js
