language: haskell
env:
  global:
  - ELM_HOME="./elm-home"
install:
  - wget http://deadfoxygrandpa.github.io/elm-travis-cache/elm
  - wget http://deadfoxygrandpa.github.io/elm-travis-cache/elm-get
  - wget http://deadfoxygrandpa.github.io/elm-travis-cache/elm-io
  - wget http://deadfoxygrandpa.github.io/elm-travis-cache/elm_home.tar.gz
  - chmod +x ./elm
  - chmod +x ./elm-get
  - chmod +x ./elm-io
  - tar -xzf elm_home.tar.gz ./
  - echo "y" | ./elm-get install evancz/automaton
  - echo "y" | ./elm-get install deadfoxygrandpa/Elm-Test
  - npm install jsdom
before_script: ./elm-io --default-ports Tests/NodeTests.elm tests.js
script:
  - ./elm --make Demo.elm
  - node --stack-size=32000 tests.js
